name: CI workflow

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Build and Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Build
        run: mvn -B package -DskipTests --file pom.xml
      - name: Run Tests
        run: mvn test
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6